spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/thinkfast
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your-secret-key-should-be-very-long-and-secure-at-least-256-bits
  token-validity-in-seconds: 86400 # 24 hours 