-- 메뉴얼 청크 테이블
CREATE TABLE IF NOT EXISTS MANUAL_CHUNKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MANUAL_ID BIGINT NOT NULL,
    CHUNK_INDEX INT NOT NULL,
    CONTENT TEXT NOT NULL,
    QDRANT_POINT_ID VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_MANUAL_ID (MANUAL_ID),
    INDEX IDX_MANUAL_CHUNK (MANUAL_ID, CHUNK_INDEX)
);

