-- 건의사항 테이블
CREATE TABLE IF NOT EXISTS SUGGESTIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    STATUS ENUM('PENDING', 'REVIEWED', 'RESOLVED') DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

