-- 챗봇 대화 이력 테이블
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(36) NOT NULL,
    USER_ID BIGINT,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT NOT NULL,
    REFERENCED_MANUAL_IDS JSON,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_SESSION_ID (SESSION_ID)
);

