DROP TABLE IF EXISTS NOTIFICATIONS;

CREATE TABLE NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    MESSAGE TEXT NOT NULL,
    REFERENCE_ID BIGINT,
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT DATETIME
);