CREATE TABLE SURVEY_RESPONSE_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SURVEY_ID BIGINT NOT NULL,
    DEVICE_ID_HASH VARCHAR(255) NOT NULL,
    IP_ADDRESS_HASH VARCHAR(255),
    RESPONDED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
