-- INSIGHT_REPORTS 테이블 수정
-- 1. SURVEY_ID에 UNIQUE 제약조건 추가
-- 2. KEYWORDS, SENTIMENT_SUMMARY를 TEXT 타입으로 변경 (JSON -> TEXT)

-- SURVEY_ID에 UNIQUE 제약조건 추가
ALTER TABLE INSIGHT_REPORTS 
ADD CONSTRAINT UK_INSIGHT_REPORTS_SURVEY_ID UNIQUE (SURVEY_ID);

-- KEYWORDS 컬럼 타입 변경 (JSON -> TEXT)
-- MariaDB/MySQL에서는 JSON 타입을 TEXT로 직접 변경할 수 없으므로
-- 임시 컬럼을 사용하여 데이터 마이그레이션
ALTER TABLE INSIGHT_REPORTS 
ADD COLUMN KEYWORDS_TEMP TEXT;

-- 기존 데이터 복사 (JSON을 TEXT로 변환)
UPDATE INSIGHT_REPORTS 
SET KEYWORDS_TEMP = CAST(KEYWORDS AS CHAR)
WHERE KEYWORDS IS NOT NULL;

-- 기존 컬럼 삭제
ALTER TABLE INSIGHT_REPORTS 
DROP COLUMN KEYWORDS;

-- 새 컬럼 이름 변경
ALTER TABLE INSIGHT_REPORTS 
CHANGE COLUMN KEYWORDS_TEMP KEYWORDS TEXT;

-- SENTIMENT_SUMMARY 컬럼 타입 변경 (JSON -> TEXT)
ALTER TABLE INSIGHT_REPORTS 
ADD COLUMN SENTIMENT_SUMMARY_TEMP TEXT;

-- 기존 데이터 복사
UPDATE INSIGHT_REPORTS 
SET SENTIMENT_SUMMARY_TEMP = CAST(SENTIMENT_SUMMARY AS CHAR)
WHERE SENTIMENT_SUMMARY IS NOT NULL;

-- 기존 컬럼 삭제
ALTER TABLE INSIGHT_REPORTS 
DROP COLUMN SENTIMENT_SUMMARY;

-- 새 컬럼 이름 변경
ALTER TABLE INSIGHT_REPORTS 
CHANGE COLUMN SENTIMENT_SUMMARY_TEMP SENTIMENT_SUMMARY TEXT;

