-- 워드클라우드 테이블 생성
CREATE TABLE IF NOT EXISTS WORD_CLOUDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_ID BIGINT NOT NULL UNIQUE,
    WORD_CLOUD_DATA TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--     FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID) ON DELETE CASCADE
);

