-- 질문별 인사이트 테이블 생성
CREATE TABLE IF NOT EXISTS QUESTION_INSIGHTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_ID BIGINT NOT NULL UNIQUE,
    INSIGHT_TEXT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--     FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID) ON DELETE CASCADE
);

