-- RESPONSES 테이블에 CREATED_AT 컬럼 추가 (nullable)
ALTER TABLE RESPONSES 
ADD COLUMN CREATED_AT TIMESTAMP NULL;

-- 기존 데이터에 대해 CREATED_AT을 현재 시간으로 설정
UPDATE RESPONSES 
SET CREATED_AT = CURRENT_TIMESTAMP
WHERE CREATED_AT IS NULL;

-- NOT NULL 제약 조건 및 기본값 추가
ALTER TABLE RESPONSES 
MODIFY COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

